--- drivers/net/wireless/ath/wcn36xx/Makefile
+++ drivers/net/wireless/ath/wcn36xx/Makefile
@@ -5,6 +5,7 @@ wcn36xx-y +=   main.o \
                txrx.o \
                smd.o \
                pmc.o \
-               debug.o
+               debug.o \
+               firmware.o
 
-wcn36xx-$(CPTCFG_NL80211_TESTMODE) += testmode.o
+wcn36xx-$(CONFIG_NL80211_TESTMODE) += testmode.o
